# Setup
# title: 
url: https://lorinbaumgarten.com/
domain: lorinbaumgarten.com
permalink: none
markdown: kramdown

lsi: false
safe: false
# source: [your repo's top level directory]
incremental: false

highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge


# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - Design.afpub


sass:
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Navbar page list
# nav:
#   - title: Blog
#     url: /archive

#   - title: About
#     url: /about

collections:
  notes:
    output: true
    permalink: /notes/:title/
