url: https://lorinbaumgarten.com/
domain: lorinbaumgarten.com
permalink: none
markdown: kramdown

lsi: false
safe: false
incremental: false

highlighter: rouge

include:
  - .nojekyll

exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - "spirit stream design.afpub"
  - obsidianToJekyll.py
  - LICENSE
  - test.py
  - CNAME
  - convertGitHistory.ipynb

destination: docs

sass:
  style: :compressed

collections:
  notes:
    output: true
    permalink: /notes/:title/
